platform :ios, '9.0'

source ‘https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git’

install! 'cocoapods', :disable_input_output_paths => true

target 'FisherySystem' do
 
#版本号 1.1.0
pod 'Masonry', :inhibit_warnings => true
#版本号 5.9.0
pod 'SDWebImage','5.9.0', :inhibit_warnings => true
#版本号 3.2.2
pod 'MJExtension', :inhibit_warnings => true
#版本号 3.6.1
pod 'MJRefresh', :inhibit_warnings => true
#版本号 0.2.0
pod 'MMLayout', :inhibit_warnings => true
#版本号 2.2.1
pod 'SDAutoLayout', :inhibit_warnings => true
#版本号 1.0.9
pod 'YYKit','1.0.9', :inhibit_warnings => true
#版本号 4.0.1
pod 'AFNetworking','4.0.1', :inhibit_warnings => true
#版本号 6.5.6
pod 'IQKeyboardManager', '6.5.6', :inhibit_warnings => true 
#版本号 1.82
pod 'SDCycleScrollView','>= 1.82', :inhibit_warnings => true

end

#消除版本警告
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
